# Generated by Django 4.2.6 on 2023-10-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_remove_notificacion_mostrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='mostrada',
            field=models.BooleanField(default=False),
        ),
    ]
