# Generated by Django 4.2.6 on 2023-10-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventarios', '0002_remove_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_inventarios.entradasuministro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_inventarios.producto')),
            ],
        ),
    ]
