# Generated by Django 4.2.6 on 2023-10-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventarios', '0003_detalleentrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='NivelReorden',
        ),
        migrations.DeleteModel(
            name='DetalleEntrada',
        ),
    ]
