# Generated by Django 4.2.6 on 2023-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventarios', '0004_remove_producto_nivelreorden_delete_detalleentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='NivelReorden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
